In [2]:
import numpy as np
import pandas as pd

from ipynb.fs.full.busiest_times_and_days import *

In [3]:
orders = pd.read_csv("D:/github/Python/Python/Maven Pizza Challenge/Resources/pizza_sales/orders.csv", encoding='utf-8')                       
order_details = pd.read_csv("D:/github/Python/Python/Maven Pizza Challenge/Resources/pizza_sales/order_details.csv", encoding='utf-8')
pizza_types = pd.read_csv("D:/github/Python/Python/Maven Pizza Challenge/Resources/pizza_sales/pizza_types.csv", encoding='ISO-8859-1')
pizzas = pd.read_csv("D:/github/Python/Python/Maven Pizza Challenge/Resources/pizza_sales/pizzas.csv", encoding='utf-8')

In [4]:
pizza_orders = pd.merge(order_details, pizzas, how='inner', on='pizza_id')
pizza_orders = pd.merge(pizza_orders, pizza_types, how='inner', on='pizza_type_id')
final_orders = pd.merge(pizza_orders, orders, how='inner', on='order_id').drop(
    columns={'ingredients', 'order_details_id', 'pizza_id'}
).sort_values(by='order_id')

final_orders['datetime'] = (final_orders['date'] + ' ' + final_orders['time']).astype('datetime64')
final_orders = final_orders.drop(
        columns={'date', 'time'}
).set_index('datetime')

final_orders['day'] = final_orders.index.day_name()
final_orders['month'] = final_orders.index.month_name()

get_orders_hour_morning(final_orders.index.hour)
get_orders_hour_afternoon(final_orders.index.hour)
get_orders_hour_evening(final_orders.index.hour)
get_orders_hour_night(final_orders.index.hour)

final_orders['time_of_day'] = get_day_category(final_orders.index.hour)
final_orders = final_orders.reset_index()

final_orders["revenue"] = final_orders["price"] * final_orders["quantity"]

final_orders = final_orders.rename(columns={'datetime': 'Datetime', 
'order_id': 'Orders Count', 'quantity': 'Orders Quantity', 
'pizza_type_id': 'Pizza Type', 'size':'Size', 'price': 'Price', 'name': 'Name', 
'category': 'Category', 'day': 'Day', 'month': 'Month', 
'time_of_day': 'Time of Day', 'revenue': 'Revenue'})

final_orders

,Datetime,Orders Count,Orders Quantity,Pizza Type,Size,Price,Name,Category,Day,Month,Time of Day,Revenue
0,2015-01-01 11:38:36,1,1,hawaiian,M,13.25,The Hawaiian Pizza,Classic,Thursday,January,Morning,13.25
1,2015-01-01 11:57:40,2,1,thai_ckn,L,20.75,The Thai Chicken Pizza,Chicken,Thursday,January,Morning,20.75
2,2015-01-01 11:57:40,2,1,mexicana,M,16.00,The Mexicana Pizza,Veggie,Thursday,January,Morning,16.00
3,2015-01-01 11:57:40,2,1,classic_dlx,M,16.00,The Classic Deluxe Pizza,Classic,Thursday,January,Morning,16.00
4,2015-01-01 11:57:40,2,1,five_cheese,L,18.50,The Five Cheese Pizza,Veggie,Thursday,January,Morning,18.50
...,...,...,...,...,...,...,...,...,...,...,...,...
48615,2015-12-31 21:23:10,21348,1,napolitana,S,12.00,The Napolitana Pizza,Classic,Thursday,December,Evening,12.00
48616,2015-12-31 21:23:10,21348,1,ckn_alfredo,M,16.75,The Chicken Alfredo Pizza,Chicken,Thursday,December,Evening,16.75
48617,2015-12-31 21:23:10,21348,1,four_cheese,L,17.95,The Four Cheese Pizza,Veggie,Thursday,December,Evening,17.95
48618,2015-12-31 22:09:54,21349,1,mexicana,L,20.25,The Mexicana Pizza,Veggie,Thursday,December,Night,20.25
48619,2015-12-31 23:02:05,21350,1,bbq_ckn,S,12.75,The Barbecue Chicken Pizza,Chicken,Thursday,December,Night,12.75

In [5]:
final_orders.to_csv("D:/github/Python/Python/Maven Pizza Challenge/final_orders.csv", encoding='utf-8')